version: 2
commands:
  install-docker-buildx:
    description: Install Docker Buildx
    steps:
      - run:
          name: Install Docker Buildx
          command: |
            mkdir -vp ~/.docker/cli-plugins/
            curl --silent -L "https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker buildx version
            sudo apt-get update && sudo apt-get install -y binfmt-support qemu-user-static
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker run --privileged --rm tonistiigi/binfmt --install all
            docker context create buildcontext
            docker buildx create buildcontext --use
jobs:
  build:
    parameters:
      resource_size:
        description: Resource agent size
        type: string
        default: medium
      repo:
        description: repository without tag, e.g. yourproject/foo
        type: string
      directory:
        description: Directory path without trailing slash relative to repo root
        type: string
    docker:
      - image: cimg/base:stable
    resource_class: << parameters.resource_size >>
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - install-docker-buildx
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run: docker buildx build --push --platform linux/arm64,linux/amd64 --tag itswhooop/tovy:latest .